{% set name = "hg-evolve" %}
{% set version = "12.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 590a75ada084fa1a668eeb6f5d5583879754372f9f108eaf5c9b2d84b898f5d0

build:
  noarch: python
  number: 0
  script: 'pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - mercurial

test:
  requires:
    - python {{ python_min }}
  imports:
    - hgext3rd
    - hgext3rd.evolve
    - hgext3rd.evolve.thirdparty
    - hgext3rd.topic

about:
  home: https://www.mercurial-scm.org/doc/evolution/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Flexible evolution of Mercurial history.
  doc_url: https://www.mercurial-scm.org/doc/evolution/
  dev_url: https://www.mercurial-scm.org/repo/evolve/

extra:
  recipe-maintainers:
    - paugier
